spring:
  datasource:
    url: jdbc:mysql://localhost:3307/magic_byte?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 1234567
    driver-class-name: com.mysql.jdbc.Driver
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris:
        - http://localhost:9200
      username: 'elastic'
      password: '6p9tqdDqpJB'
      connection-timeout: 10


server:
  port: 3302
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
data:
  env: config-eureka-dev
  user:
    username: eureka-client-user
    password: 1291029104




minio:
  domain: "http://10.206.0.11:9000"
  accessKey: "minio"
  secretKey: "%SQknI%%o5Va82F#akH"


tencent:
  secretId: "AKIDmT3PGsEAXfaGfpqmZ75oPmwqdPCks8NM"
  secretKey: "vbz7pqoY1FEcnxtomW2LPEmGfrobPxRm"





swagger:
  apiInfoTitle: "Magic Byte Api"
  apiInfoVersion: "v1.0"
  apiInfoDescription: "Magic Byte Api 文档"
  apiInfoTermsOfServiceUrl: "/doc.html"
  apiInfoLicense: ""
  apiInfoLicenseUrl: ""
